# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Book.create(:title => "The Lord of the Rings", :author => "JRR Tolkien")
Book.create(:title => "Pride and Prejudice", :author => "Jane Austen")
Book.create(:title => "His Dark Materials", :author => "Philip Pullman")
Book.create(:title => "The Hitchhiker's Guide to the Galaxy", :author => "Douglas Adams")
Book.create(:title => "Harry Potter and the Goblet of Fire", :author => "JK Rowling")
Book.create(:title => "To Kill a Mockingbird", :author => "Harper Lee")
Book.create(:title => "Winnie the Pooh", :author => "AA Milne")
Book.create(:title => "Nineteen Eighty-Four", :author => "George Orwell")
Book.create(:title => "The Lion, the Witch and the Wardrobe", :author => "CS Lewis")
Book.create(:title => "Jane Eyre", :author => "Charlotte Bronte")
Book.create(:title => "Catch-22", :author => "Joseph Heller")
Book.create(:title => "Wuthering Heights", :author => "Emily Bronte")
Book.create(:title => "Birdsong", :author => "Sebastian Faulks")
Book.create(:title => "Rebecca", :author => "Daphne du Maurier")
Book.create(:title => "The Catcher in the Rye", :author => "JD Salinger")
Book.create(:title => "The Wind in the Willows", :author => "Kenneth Grahame")
Book.create(:title => "Great Expectations", :author => "Charles Dickens")
Book.create(:title => "Little Women", :author => "Louisa May Alcott")
Book.create(:title => "Captain Corelli's Mandolin", :author => "Louis de Bernieres")
Book.create(:title => "War and Peace", :author => "Leo Tolstoy")
Book.create(:title => "Gone with the Wind", :author => "Margaret Mitchell")
Book.create(:title => "Harry Potter And The Philosopher's Stone", :author => "JK Rowling")
Book.create(:title => "Harry Potter And The Chamber Of Secrets", :author => "JK Rowling")
Book.create(:title => "Harry Potter And The Prisoner Of Azkaban", :author => "JK Rowling")
Book.create(:title => "The Hobbit", :author => "JRR Tolkien")
Book.create(:title => "Tess Of The D'Urbervilles", :author => "Thomas Hardy")
Book.create(:title => "Middlemarch", :author => "George Eliot")
Book.create(:title => "A Prayer For Owen Meany", :author => "John Irving")
Book.create(:title => "The Grapes Of Wrath", :author => "John Steinbeck")
Book.create(:title => "Alice's Adventures In Wonderland", :author => "Lewis Carroll")
Book.create(:title => "The Story Of Tracy Beaker", :author => "Jacqueline Wilson")
Book.create(:title => "One Hundred Years Of Solitude", :author => "Gabriel Garcia Marquez")
Book.create(:title => "The Pillars Of The Earth", :author => "Ken Follett")
Book.create(:title => "David Copperfield", :author => "Charles Dickens")
Book.create(:title => "Charlie And The Chocolate Factory", :author => "Roald Dahl")
Book.create(:title => "Treasure Island", :author => "Robert Louis Stevenson")
Book.create(:title => "A Town Like Alice", :author => "Nevil Shute")
Book.create(:title => "Persuasion", :author => "Jane Austen")
Book.create(:title => "Dune", :author => "Frank Herbert")
Book.create(:title => "Emma", :author => "Jane Austen")
Book.create(:title => "Anne Of Green Gables", :author => "LM Montgomery")
Book.create(:title => "Watership Down", :author => "Richard Adams")
Book.create(:title => "The Great Gatsby", :author => "F Scott Fitzgerald")
Book.create(:title => "The Count Of Monte Cristo", :author => "Alexandre Dumas")
Book.create(:title => "Brideshead Revisited", :author => "Evelyn Waugh")
Book.create(:title => "Animal Farm", :author => "George Orwell")
Book.create(:title => "A Christmas Carol", :author => "Charles Dickens")
Book.create(:title => "Far From The Madding Crowd", :author => "Thomas Hardy")
Book.create(:title => "Goodnight Mister Tom", :author => "Michelle Magorian")
Book.create(:title => "The Shell Seekers", :author => "Rosamunde Pilcher")
Book.create(:title => "The Secret Garden", :author => "Frances Hodgson Burnett")
Book.create(:title => "Of Mice And Men", :author => "John Steinbeck")
Book.create(:title => "The Stand", :author => "Stephen King")
Book.create(:title => "Anna Karenina", :author => "Leo Tolstoy")
Book.create(:title => "A Suitable Boy", :author => "Vikram Seth")
Book.create(:title => "The BFG", :author => "Roald Dahl")
Book.create(:title => "Swallows And Amazons", :author => "Arthur Ransome")
Book.create(:title => "Black Beauty", :author => "Anna Sewell")
Book.create(:title => "Artemis Fowl", :author => "Eoin Colfer")
Book.create(:title => "Crime And Punishment", :author => "Fyodor Dostoyevsky")
Book.create(:title => "Noughts And Crosses", :author => "Malorie Blackman")
Book.create(:title => "Memoirs Of A Geisha", :author => "Arthur Golden")
Book.create(:title => "A Tale Of Two Cities", :author => "Charles Dickens")
Book.create(:title => "The Thorn Birds", :author => "Colleen McCollough")
Book.create(:title => "Mort", :author => "Terry Pratchett")
Book.create(:title => "The Magic Faraway Tree", :author => "Enid Blyton")
Book.create(:title => "The Magus", :author => "John Fowles")
Book.create(:title => "Good Omens", :author => "Terry Pratchett and Neil Gaiman")
Book.create(:title => "Guards! Guards!", :author => "Terry Pratchett")
Book.create(:title => "Lord Of The Flies", :author => "William Golding")
Book.create(:title => "Perfume", :author => "Patrick Suskind")
Book.create(:title => "The Ragged Trousered Philanthropists", :author => "Robert Tressell")
Book.create(:title => "Night Watch", :author => "Terry Pratchett")
Book.create(:title => "Matilda", :author => "Roald Dahl")
Book.create(:title => "Bridget Jones's Diary", :author => "Helen Fielding")
Book.create(:title => "The Secret History", :author => "Donna Tartt")
Book.create(:title => "The Woman In White", :author => "Wilkie Collins")
Book.create(:title => "Ulysses", :author => "James Joyce")
Book.create(:title => "Bleak House", :author => "Charles Dickens")
Book.create(:title => "Double Act", :author => "Jacqueline Wilson")
Book.create(:title => "The Twits", :author => "Roald Dahl")
Book.create(:title => "I Capture The Castle", :author => "Dodie Smith")
Book.create(:title => "Holes", :author => "Louis Sachar")
Book.create(:title => "Gormenghast", :author => "Mervyn Peake")
Book.create(:title => "The God Of Small Things", :author => "Arundhati Roy")
Book.create(:title => "Vicky Angel", :author => "Jacqueline Wilson")
Book.create(:title => "Brave New World", :author => "Aldous Huxley")
Book.create(:title => "Cold Comfort Farm", :author => "Stella Gibbons")
Book.create(:title => "Magician", :author => "Raymond E Feist")
Book.create(:title => "On The Road", :author => "Jack Kerouac")
Book.create(:title => "The Godfather", :author => "Mario Puzo")
Book.create(:title => "The Clan Of The Cave Bear", :author => "Jean M Auel")
Book.create(:title => "The Colour Of Magic", :author => "Terry Pratchett")
Book.create(:title => "The Alchemist", :author => "Paulo Coelho")
Book.create(:title => "Katherine", :author => "Anya Seton")
Book.create(:title => "Kane And Abel", :author => "Jeffrey Archer")
Book.create(:title => "Love In The Time Of Cholera", :author => "Gabriel Garcia Marquez")
Book.create(:title => "Girls In Love", :author => "Jacqueline Wilson")
Book.create(:title => "The Princess Diaries", :author => "Meg Cabot")
Book.create(:title => "Midnight's Children", :author => "Salman Rushdie")